/*
 * Copyright (c) 2026, osrsloadout
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.osrsloadout;

import java.util.Arrays;
import java.util.Collections;
import static org.junit.Assert.assertEquals;
import org.junit.Test;

/**
 * The expected strings here were produced with JavaScript's Number#toString(36), which is the decoder on the
 * other end. That is the point of the test: Java and the browser have to agree, and asserting against a
 * literal that was generated by the other implementation is the only way to catch a divergence.
 */
public class LoadoutLinkTest
{
	@Test
	public void packsAscendingBase36()
	{
		// Abyssal whip (4151), Bandos chestplate (11832), Armadyl crossbow (11802), out of order on input.
		assertEquals("v2~37b.93u.94o", LoadoutLink.pack(Arrays.asList(11832, 4151, 11802)));
	}

	@Test
	public void deDuplicates()
	{
		assertEquals("v2~37b", LoadoutLink.pack(Arrays.asList(4151, 4151, 4151)));
	}

	@Test
	public void dropsNonPositiveIds()
	{
		// Empty item container slots report -1, and the caller is not the only possible caller.
		assertEquals("v2~rn", LoadoutLink.pack(Arrays.asList(-1, 0, 995)));
	}

	@Test
	public void emptySetIsJustThePrefix()
	{
		// The site rejects this, so the plugin must never send it; pinning the shape keeps that check honest.
		assertEquals("v2~", LoadoutLink.pack(Collections.emptyList()));
	}

	@Test
	public void urlPutsThePayloadInTheFragment()
	{
		// Everything after '#' stays in the browser. If this ever became a query string the privacy claim in
		// the README would quietly stop being true.
		assertEquals("https://www.osrsloadout.com/#v2~37b", LoadoutLink.url(LoadoutLink.pack(Collections.singletonList(4151))));
	}
}
